sudo: required
services:
  - docker

before_install:
  - docker build -t padmakumarnkg/bmi-app-client -f ./client/Dockerfile.dev ./Client

script:
  - docker run padmakumarnkg/bmi-app-client npm test -- --coverage

after_success:
  - docker build -t padmakumarnkg/bmi-app-client ./Client
  - docker build -t padmakumarnkg/bmi-app-nginx ./nginx
  - docker build -t padmakumarnkg/bmi-app-server ./Cerver  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push padmakumarnkg/bmi-app-Client
  - docker push padmakumarnkg/bmi-app-nginx
  - docker push padmakumarnkg/bmi-app-Server
  