apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-app-client
spec:
  selector:
    matchLabels:
      app: bmi-app-client
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: bmi-app-client
        tier: frontend
        track: stable
    spec:
      containers:
        - name: bmi-app-client
          image: "padmakumarnkg/bmi-app-client"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: bmi-app-client-service
spec:
    type: ClusterIP
    selector:
        app: bmi-app-client
        tier: frontend
    ports:
        - protocol: TCP
          port: 3000
          targetPort: http