apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmi-app-server
spec:
  selector:
    matchLabels:
      app: bmi-app-server
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: bmi-app-server
        tier: backend
        track: stable
    spec:
      containers:
        - name: bmi-app-server
          image: "padmakumarnkg/bmi-app-server"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: bmi-app-server-service
spec:
    type: ClusterIP
    selector:
        app: bmi-app-server
        tier: backend
    ports:
        - protocol: TCP
          port: 5000
          targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bmi-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: kubernetes.docker.internal    
    http:
      paths:
      - path: /api/(.*)      
        backend:
          serviceName: bmi-app-server-service
          servicePort: 5000          